<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <Product>Umbraco.Community.Sanitiser.Users</Product>
    <PackageId>Umbraco.Community.Sanitiser.Users</PackageId>
    <Title>Sanitiser Users</Title>
    <Description>Sanitisation strategy that removes Umbraco backoffice users (except the Super Admin) and their cached data on startup.</Description>
    <RootNamespace>Umbraco.Community.Sanitiser</RootNamespace>
    <AssemblyName>Umbraco.Community.Sanitiser.Users</AssemblyName>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2025.2.4" />
    <ProjectReference Include="..\Sanitiser.Core\Sanitiser.Core.csproj" />
  </ItemGroup>

</Project>
