<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <Product>Umbraco.Community.Sanitiser</Product>
    <PackageId>Umbraco.Community.Sanitiser</PackageId>
    <Title>Sanitiser</Title>
    <Description>When enabled, this package automatically removes or anonymises personal data (users and members) from your Umbraco website on startup.</Description>
    <RootNamespace>Umbraco.Community.Sanitiser</RootNamespace>
    <AssemblyName>Umbraco.Community.Sanitiser</AssemblyName>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JetBrains.Annotations" Version="2025.2.4" />
    <ProjectReference Include="..\Sanitiser.Core\Sanitiser.Core.csproj" />
  </ItemGroup>

</Project>
