name: Release Package

on:
    push:
        tags:
            - "[0-9]+.[0-9]+.[0-9]+"

jobs:
    build:

        runs-on: ubuntu-latest

        steps:

            -   name: Checkout repository
                uses: actions/checkout@v4

            -   name: Setup .NET
                uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: 8.0.x

            -   name: Build project
                run: dotnet build src/Sanitiser/Sanitiser.csproj --configuration Release

            -   name: Package project
                run: dotnet pack src/Sanitiser/Sanitiser.csproj --configuration Release

            -   name: Push to NuGet
                run: dotnet nuget push **/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
